spring:
  application:
    name: sms-gateway
  profiles:
    active: aws

jsonplaceholder:
  base-url: https://jsonplaceholder.typicode.com

feign:
  client:
    config:
      default:
        connectTimeout: ${FEIGN_CONNECT_TIMEOUT:5000}
        readTimeout: ${FEIGN_READ_TIMEOUT:5000}
        loggerLevel: FULL
  httpclient:
    enabled: false
  okhttp:
    enabled: true

aws:
  accessKey: ${AWS_ACCESS_KEY}
  secretKey: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION}
  sms:
    originationIdentityPoolArn: ${AWS_SMS_ORIGINATION_IDENTITY_POOL_ARN}
    configurationSetName: ${AWS_SMS_CONFIGURATION_SET_NAME}
    baseUrl: ${AWS_SMS_BASE_URL}

twilio:
  accountSid: ${TWILIO_ACCOUNT_SID}
  authToken: ${TWILIO_AUTH_TOKEN}
  sms:
    baseUrl: ${TWILIO_SMS_BASE_URL}
    fromNumber: ${TWILIO_SMS_FROM_NUMBER}



logging:
  level:
    dev.miracode.sms.infrastructure.aws.client: DEBUG
    feign: DEBUG


