spring:
  application:
    name: sms-gateway

jsonplaceholder:
  base-url: https://jsonplaceholder.typicode.com

feign:
  client:
    config:
      default:
        connectTimeout: ${FEIGN_CONNECT_TIMEOUT:5000}
        readTimeout: ${FEIGN_READ_TIMEOUT:5000}
        loggerLevel: FULL
  httpclient:
    enabled: false
  okhttp:
    enabled: true

logging:
  level:
    dev.miracode.sms.client: DEBUG
    feign: DEBUG


